version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:12

jobs:
  prepare:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_works
workflows:
  version: 2
  prepare_publish:
    jobs:
      - prepare:
          context: .env
          filters:
            branches:
              only:
                - master
      - semantic-release:
          requires:
            - prepare

